### ISSUE TITLE
Complete all the steps in the prelaunch checklist for starting an open source project

### ISSUE THREAD

**Issue by sripravan** [yakshavingdevs/datadance#14]
Reference Guide: https://opensource.guide/starting-a-project/

### Checklist:
**Documentation**

- [x] Project has a LICENSE file with an open source license
- [ ] Project has basic documentation (README, CONTRIBUTING, CODE_OF_CONDUCT)
- [x] The name is easy to remember, gives some idea of what the project does, and does not conflict with an existing project or infringe on trademarks
- [x] The issue queue is up-to-date, with issues clearly organized and labeled

**Code**

- [ ] Project uses consistent code conventions and clear function/method/variable names
- [ ] The code is clearly commented, documenting intentions and edge cases
- [x] There are no sensitive materials in the revision history, issues, or pull requests (for example, passwords or other non-public information)
